### ISSUE TITLE
bash.sh

### ISSUE THREAD

**Issue by shaunstanislaus** [mysql/mysql-utilities#13]
Collecting mysql-utilities
  Using cached mysql-utilities-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5k/f1v65n8d7dxg2_72t4kw5nvr0000gn/T/pip-build-qQGOR1/mysql-utilities/setup.py", line 36, in <module>
        from info import META_INFO, INSTALL
    ImportError: No module named info

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5k/f1v65n8d7dxg2_72t4kw5nvr0000gn/T/pip-build-qQGOR1/mysql-utilities/
FAIL: 1
shaunstanislaus@Master: ~ $ pip install mysql-utilities                                 [23:18:29]
Requirement already satisfied (use --upgrade to upgrade): mysql-utilities in /Library/Python/2.7/site-packages
shaunstanislaus@Master: ~ $ pip install --upgrade mysql-utilities                       [23:20:24]
Collecting mysql-utilities
  Using cached mysql-utilities-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5k/f1v65n8d7dxg2_72t4kw5nvr0000gn/T/pip-build-YknaJR/mysql-utilities/setup.py", line 36, in <module>
        from info import META_INFO, INSTALL
    ImportError: No module named info

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5k/f1v65n8d7dxg2_72t4kw5nvr0000gn/T/pip-build-YknaJR/mysql-utilities/
FAIL: 1

**Comment by JDFagan** [comment]
I also ran into this same error:

`$ pip install mysql-utilities
Collecting mysql-utilities
  Using cached mysql-utilities-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9k/p86ywk316lnc2mdg5yxkn6cc0000gn/T/pip-build-OZ9Ckc/mysql-utilities/setup.py", line 36, in <module>
        from info import META_INFO, INSTALL
    ImportError: No module named info

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9k/p86ywk316lnc2mdg5yxkn6cc0000gn/T/pip-build-OZ9Ckc/mysql-utilities/`
