### ISSUE TITLE
No module named connector

### ISSUE THREAD

**Issue by infotek** [mysql/mysql-utilities#23]
Ubuntu 16.04.3 LTS

root@cwmon02:~/mysql-utilities# mysqlbinlogpurge
Traceback (most recent call last):
  File "/usr/local/bin/mysqlbinlogpurge", line 28, in <module>
    from mysql.utilities.command.binlog_admin import binlog_purge
  File "/usr/local/lib/python2.7/dist-packages/mysql/utilities/command/binlog_admin.py", line 38, in <module>
    from mysql.utilities.common.server import Server
  File "/usr/local/lib/python2.7/dist-packages/mysql/utilities/common/server.py", line 33, in <module>
    import mysql.connector
ImportError: No module named connector

Despite being detected during install

root@cwmon02:~/mysql-utilities# python2.7 ./setup.py install
checking mysql for packages to distribute
packages found: ['mysql', 'mysql.utilities', 'mysql.utilities.command', 'mysql.utilities.common']
scripts found: ['scripts/mysqlrplsync.py', 'scripts/mysqldbexport.py', 'scripts/mysqlfailover.py', 'scripts/mysqlprocgrep.py', 'scripts/mysqlrplshow.py', 'scripts/mysqlgrants.py', 'scripts/mysqlslavetrx.py', 'scripts/mysqlrpladmin.py', 'scripts/mysqluc.py', 'scripts/mysqlserverinfo.py', 'scripts/mysqlauditadmin.py', 'scripts/mysqlrplms.py', 'scripts/mysqlauditgrep.py', 'scripts/mysqlfrm.py', 'scripts/mysqldiff.py', 'scripts/mysqldbcompare.py', 'scripts/mysqlreplicate.py', 'scripts/mysqluserclone.py', 'scripts/mysqlbinlogrotate.py', 'scripts/mysqlrplcheck.py', 'scripts/mysqlmetagrep.py', 'scripts/mysqlbinlogmove.py', 'scripts/mysqlindexcheck.py', 'scripts/mysqldbimport.py', 'scripts/mysqldiskusage.py', 'scripts/mysqlserverclone.py', 'scripts/mysqldbcopy.py', 'scripts/mysqlbinlogpurge.py']
package set set(['mysql.utilities.common', 'mysql.utilities.command', 'mysql.utilities', 'mysql'])
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
copying build/scripts-2.7/mysqlreplicate -> /usr/local/bin
copying build/scripts-2.7/mysqldiskusage -> /usr/local/bin
copying build/scripts-2.7/mysqlrplms -> /usr/local/bin
copying build/scripts-2.7/mysqlbinlogrotate -> /usr/local/bin
copying build/scripts-2.7/mysqldiff -> /usr/local/bin
copying build/scripts-2.7/mysqlfailover -> /usr/local/bin
copying build/scripts-2.7/mysqlrplshow -> /usr/local/bin
copying build/scripts-2.7/mysqlauditgrep -> /usr/local/bin
copying build/scripts-2.7/mysqlbinlogpurge -> /usr/local/bin
copying build/scripts-2.7/mysqlmetagrep -> /usr/local/bin
copying build/scripts-2.7/mysqldbexport -> /usr/local/bin
copying build/scripts-2.7/mysqldbcopy -> /usr/local/bin
copying build/scripts-2.7/mysqlbinlogmove -> /usr/local/bin
copying build/scripts-2.7/mysqlserverinfo -> /usr/local/bin
copying build/scripts-2.7/mysqlrplcheck -> /usr/local/bin
copying build/scripts-2.7/mysqlrpladmin -> /usr/local/bin
copying build/scripts-2.7/mysqlindexcheck -> /usr/local/bin
copying build/scripts-2.7/mysqluc -> /usr/local/bin
copying build/scripts-2.7/mysqlfrm -> /usr/local/bin
copying build/scripts-2.7/mysqlprocgrep -> /usr/local/bin
copying build/scripts-2.7/mysqlslavetrx -> /usr/local/bin
copying build/scripts-2.7/mysqldbimport -> /usr/local/bin
copying build/scripts-2.7/mysqlserverclone -> /usr/local/bin
copying build/scripts-2.7/mysqlauditadmin -> /usr/local/bin
copying build/scripts-2.7/mysqlgrants -> /usr/local/bin
copying build/scripts-2.7/mysqlrplsync -> /usr/local/bin
copying build/scripts-2.7/mysqldbcompare -> /usr/local/bin
copying build/scripts-2.7/mysqluserclone -> /usr/local/bin
changing mode of /usr/local/bin/mysqlreplicate to 755
changing mode of /usr/local/bin/mysqldiskusage to 755
changing mode of /usr/local/bin/mysqlrplms to 755
changing mode of /usr/local/bin/mysqlbinlogrotate to 755
changing mode of /usr/local/bin/mysqldiff to 755
changing mode of /usr/local/bin/mysqlfailover to 755
changing mode of /usr/local/bin/mysqlrplshow to 755
changing mode of /usr/local/bin/mysqlauditgrep to 755
changing mode of /usr/local/bin/mysqlbinlogpurge to 755
changing mode of /usr/local/bin/mysqlmetagrep to 755
changing mode of /usr/local/bin/mysqldbexport to 755
changing mode of /usr/local/bin/mysqldbcopy to 755
changing mode of /usr/local/bin/mysqlbinlogmove to 755
changing mode of /usr/local/bin/mysqlserverinfo to 755
changing mode of /usr/local/bin/mysqlrplcheck to 755
changing mode of /usr/local/bin/mysqlrpladmin to 755
changing mode of /usr/local/bin/mysqlindexcheck to 755
changing mode of /usr/local/bin/mysqluc to 755
changing mode of /usr/local/bin/mysqlfrm to 755
changing mode of /usr/local/bin/mysqlprocgrep to 755
changing mode of /usr/local/bin/mysqlslavetrx to 755
changing mode of /usr/local/bin/mysqldbimport to 755
changing mode of /usr/local/bin/mysqlserverclone to 755
changing mode of /usr/local/bin/mysqlauditadmin to 755
changing mode of /usr/local/bin/mysqlgrants to 755
changing mode of /usr/local/bin/mysqlrplsync to 755
changing mode of /usr/local/bin/mysqldbcompare to 755
changing mode of /usr/local/bin/mysqluserclone to 755
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/mysql_utilities-1.6.5.egg-info
Writing /usr/local/lib/python2.7/dist-packages/mysql_utilities-1.6.5.egg-info

**Comment by infotek** [comment]
mysql-connector failed to install due to "Unable to find Protobuf include directory."
Installing an older version of mysql-connector resolved the issue.

pip install mysql-connector==2.1.6
