### ISSUE TITLE
Grant statements from AWS RDS are incorrectly parsed because of mandatory quoted password in regex

### ISSUE THREAD

**Issue by arphen** [mysql/mysql-utilities#30]
Hi,
This is a follow up to BUG#21653352 and its corresponding fix ([commit](https://github.com/mysql/mysql-utilities/commit/ad7ea54fd89f1c702bd0d22c174cc386b9f2939f)). The fix is not complete, since [line 690](https://github.com/mysql/mysql-utilities/blob/master/mysql/utilities/common/user.py#L690) still relies on single quotes and does not accept the masked ''\<secret\>" string (see original commit).

I'm encountering the issue when trying to use `mysqluserclone`:

```
mysqluserclone --source peter:dog@localhost:3308 peter@% peter2:cat@% --include-global-privileges --verbose --force
```
creates
```
ARNING: Using a password on the command line interface can be insecure.
# Source on localhost: ... connected.
# Cloning 1 users...
# Cloning peter@% to user peter2:cat@% 
CREATE USER 'peter3'@'%' IDENTIFIED BY 'secret'
Traceback (most recent call last):
  File "/home/swozny/prt/prt/venv/bin/mysqluserclone", line 199, in <module>
    new_user_list, options)
  File "/home/swozny/prt/prt/venv/local/lib/python2.7/site-packages/mysql/utilities/command/userclone.py", line 216, in clone_user
    user_source.clone(new_user, destination, global_privs)
  File "/home/swozny/prt/prt/venv/local/lib/python2.7/site-packages/mysql/utilities/common/user.py", line 690, in clone
    end = grant.index("'", start + len(search_str) + 2) + 2
ValueError: substring not found
```

**Comment by JDFagan** [comment]
I ran into this exact same issue.  I see you have a fix for it - any idea when it will be merged/released so I can make use of the fix?

**Comment by arphen** [comment]
I gave up. I don't know how this repository is maintained and noone ever came back to me on this.
My fix was deleting the database
